openapi: 3.0.0
info:
  version: 1.0.0
  title: Products
  description: 'Service to service'
  contact:
    email: afjimene@gmail.com
paths:
  /service-api/productsByClient/{clientId}:
    get:
      tags:
        - products
      summary: Find product by clientId
      description: get a list of product from a client
      operationId: getProductsByClientId
      parameters:
        - name: clientId
          in: path
          description: ID of client
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'
        "405":
          description: Invalid input
  /service-api/transaction:
    post:
      tag:
        - products
      summary: update balance Product
      description: Update balance in a product
      operationId: update balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: product not found
components:
  schemas:
    Product:
      type: object
      properties:
        accountType:
          type: string
        accountNumber:
          type: integer
          format: int64
        balance:
          type: number
        exentGMF:
          type: boolean
        clientId:
          type: integer
          format: int64
    ProductListResponse:
      type: object
      required:
        - products
      properties:
        products:
          type: array
          description: List of mapped products.
          items:
            $ref: '#/components/schemas/Product'
    Transaction:
      type: object
      required:
        - accountNumber
        - transactionType
        - amount
      properties:
        accountNumber:
          type: integer
          format: int64
        transactionType:
          type: string
        amount:
          type: number
        targetAccount:
          type: integer
          format: int64