openapi: 3.0.0
info:
  version: 1.0.0
  title: Products
  description: ''
  contact:
    email: afjimene@gmail.com
paths:
  /product:
    post:
      tags:
        - products
      summary: Create a new product
      description: Create a new product using full information
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "405":
          description: Invalid input
  /product/activateProduct/{accountNumber}:
    put:
      tags:
        - products
      summary: activate Product
      description: Activate a product
      operationId: activateProductsByAccountNumber
      parameters:
        - name: accountNumber
          in: path
          description: ID of product
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: product not found
  /product/deactivateProduct/{accountNumber}:
    put:
      tags:
        - products
      summary: deactivate Product
      description: Deactivate a product
      operationId: deactivateProductsByAccountNumber
      parameters:
        - name: accountNumber
          in: path
          description: ID of product
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: product not found
  /product/cancelProduct/{accountNumber}:
    put:
      tags:
        - products
      summary: cancel Product
      description: Cancel a product
      operationId: cancelProductsByAccountNumber
      parameters:
        - name: accountNumber
          in: path
          description: ID of product
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: product not found
components:
  schemas:
    Product:
      type: object
      required:
        - accountType
        - exentGMF
        - clientId
      properties:
        accountType:
          type: string
        accountNumber:
          type: integer
          format: int64
        exentGMF:
          type: boolean
        clientId:
          type: integer
          format: int64