openapi: 3.0.0
info:
  version: 1.0.0
  title: Transactions
  description: ''
  contact:
    email: afjimene@gmail.com
paths:
  /transaction:
    post:
      tags:
        - transactions
      summary: Create a new transaction
      description: Create a new transaction using full information
      operationId: createTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        "201":
          description: Successful operation
        "405":
          description: Invalid input
components:
  schemas:
    Transaction:
      type: object
      required:
        - accountNumber
        - transactionType
        - amount
      properties:
        accountNumber:
          type: integer
          format: int64
        transactionType:
          type: string
        amount:
          type: number
        targetAccount:
          type: integer
          format: int64
