openapi: 3.0.0
info:
  version: 1.0.0
  title: Clients
  description: ''
  contact:
    email: afjimene@gmail.com
paths:
  /client:
    post:
      tags:
        - clients
      summary: Create a new client
      description: Create a new client using full information
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClient'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClient'
        "405":
          description: Invalid input
    put:
      tags:
        - clients
      summary: Update a existent client
      description: Update an existent client using full information
      operationId: updateClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClient'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateClient'
        "405":
          description: Invalid input
components:
  schemas:
    CreateClient:
      type: object
      required:
        - idType
        - idNumber
        - names
        - surnames
        - email
        - birthDate
      properties:
        idType:
          type: string
        idNumber:
          type: string
        names:
          type: string
        surnames:
          type: string
        email:
          type: string
        birthDate:
          type: string
    UpdateClient:
      type: object
      required:
        - id
        - idType
        - idNumber
        - names
        - surnames
        - email
        - birthDate
      properties:
        id:
          type: number
          format: int64
        idType:
          type: string
        idNumber:
          type: string
        names:
          type: string
        surnames:
          type: string
        email:
          type: string
        birthDate:
          type: string